variables:
  DOCKER_REGISTRY: docker.io
  DOCKERHUB_USERNAME: "alexandrevb" 

  # Variables Kube namespaces
  KUBE_NAMESPACE_dev: dev
  KUBE_NAMESPACE_staging: staging
  KUBE_NAMESPACE_prod: prod

image: docker:20.10

services:
  - docker:dind

before_script:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/gitlab-exam"
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-gateway:latest" ./gateway/
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-orders:latest" ./orders/
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-users:latest" ./users/

    - docker push "$DOCKERHUB_USERNAME/gitlab-exam-gateway:latest"
    - docker push "$DOCKERHUB_USERNAME/gitlab-exam-orders:latest"
    - docker push "$DOCKERHUB_USERNAME/gitlab-exam-users:latest"
