variables:
  DOCKER_REGISTRY: docker.io
  DOCKERHUB_USERNAME: "alexandrevb" 

  # Variables Kube namespaces
  KUBE_NAMESPACE_dev: dev
  KUBE_NAMESPACE_staging: staging
  KUBE_NAMESPACE_prod: prod

image: docker:20.10

services:
  - docker:dind

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/gitlab-exam"
    # Utilise DockerHub pour le tag de l'image
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-gateway:latest" ./gateway/
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-orders:latest" ./orders/
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-users:latest" ./users/
