variables:
  DOCKER_REGISTRY: docker.io
  DOCKERHUB_USERNAME: "alexandrevb" 

default:
  image: python:3.11
  services:
    - docker:24.0.5-dind

before_script:
  - apt-get update && apt-get install -y sudo curl
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

stages:
  - build
  - deploy_dev
  - deploy_QA
  - deploy_staging
  - deploy_prod

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! $DOCKER_REGISTRY/$DOCKERHUB_USERNAME/gitlab-exam"
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-gateway:latest" ./gateway/
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-orders:latest" ./orders/
    - docker build -t "$DOCKERHUB_USERNAME/gitlab-exam-users:latest" ./users/

    - docker push "$DOCKERHUB_USERNAME/gitlab-exam-gateway:latest"
    - docker push "$DOCKERHUB_USERNAME/gitlab-exam-orders:latest"
    - docker push "$DOCKERHUB_USERNAME/gitlab-exam-users:latest"


deploy_dev:
  stage: deploy_dev
  script:
    - rm -Rf .kube
    - mkdir .kube
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install app helm/ --values=values.yml --namespace dev

deploy_QA:
  stage: deploy_QA
  script:
    - rm -Rf .kube
    - mkdir .kube
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install app helm/ --values=values.yml --namespace qa

deploy_staging:
  stage: deploy_staging
  script:
    - rm -Rf .kube
    - mkdir .kube
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install app helm/ --values=values.yml --namespace staging
      
deploy_prod:
  stage: deploy_prod
  script:
    - rm -Rf .kube
    - mkdir .kube
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install app helm/ --values=values.yml --namespace prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
