variables:
  # The domain used for the live deploy_prodment
  KUBE_NAMESPACE_dev: dev
  KUBE_NAMESPACE_staging: staging
  KUBE_NAMESPACE_prod: prod

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! $CI_REGISTRY_IMAGE"
    - docker build -t "$CI_REGISTRY_IMAGE/$S_GATEWAY:latest" ./gateway/
    - docker build -t "$CI_REGISTRY_IMAGE/$S_ORDERS:latest" ./orders/
    - docker build -t "$CI_REGISTRY_IMAGE/$S_USERS:latest" ./users/


push:
  stage: push
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! $CI_REGISTRY_IMAGE"

