apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: {{ .Values.users.image }}
          command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
          ports:
            - containerPort: 8000

