apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: {{ .Values.orders.image }}
          command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
          ports:
            - containerPort: 8000

