apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: {{ .Values.gateway.image }}
          command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
          ports:
            - containerPort: 8000
          env:
            - name: USERS_SERVICE_URL
              value: "{{ .Values.gateway.env.USERS_SERVICE_URL }}"
            - name: ORDERS_SERVICE_URL
              value: "{{ .Values.gateway.env.ORDERS_SERVICE_URL }}"

