apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.service.port }}
      targetPort: 8000

