apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  type: {{ .Values.orders.service.type }}
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: {{ .Values.orders.service.port }}
      targetPort: 8000

