apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: {{ .Values.users.service.type }}
  selector:
    app: users
  ports:
    - protocol: TCP
      port: {{ .Values.users.service.port }}
      targetPort: 8000

