apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: alexandrevb/gitlab-exam-gateway:latest
          command: ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0"]
          ports:
            - containerPort: 8000
          env:
            - name: USERS_SERVICE_URL
              value: "http://users:8000"
            - name: ORDERS_SERVICE_URL
              value: "http://orders:8000"
