replicaCount: 1

image:
  pullPolicy: IfNotPresent

gateway:
  image: alexandrevb/gitlab-exam-gateway:latest
  service:
    type: LoadBalancer
    port: 8001
  env:
    USERS_SERVICE_URL: "http://users:8000"
    ORDERS_SERVICE_URL: "http://orders:8000"

orders:
  image: alexandrevb/gitlab-exam-orders:latest
  service:
    type: ClusterIP
    port: 8003

users:
  image: alexandrevb/gitlab-exam-users:latest
  service:
    type: ClusterIP
    port: 8003
